# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 'AsCom-TukAgentPool'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: /home/vsts/.npm
    restoreKeys: npm | $(Agent.OS) | package-lock.json
  displayName: Cache NPM packages
- task: CacheBeta@1
  inputs:
    key: cypress | $(Agent.OS) | package-lock.json
    path: /home/vsts/.cache/Cypress
    restoreKeys: cypress | $(Agent.OS) | package-lock.json      
  displayName: Cache Cypress binary

- script: |
    npm ci
  displayName: 'npm install'

- script: |
    ./node_modules/.bin/cypress verify
  displayName: 'Cypress Verify'

- script: |
    ./node_modules/.bin/cypress run --spec 'cypress\integration\environment\staging\staging_spec.js' --browser electron
  displayName: 'Cypress Test'
  continueOnError: true